apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "plausible.fullname" . }}-clickhouse-data
  labels:
    {{- include "plausible.clickhouse.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.clickhouse.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.clickhouse.persistence.size }} 