apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "plausible.fullname" . }}-clickhouse
  labels:
    {{- include "plausible.clickhouse.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "plausible.clickhouse.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "plausible.clickhouse.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: clickhouse
          image: "{{ .Values.clickhouse.image.repository }}:{{ .Values.clickhouse.image.tag }}"
          imagePullPolicy: {{ .Values.clickhouse.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8123
            - name: native
              containerPort: 9000
          resources:
            {{- toYaml .Values.resources.clickhouse | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/clickhouse
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "plausible.fullname" . }}-clickhouse-data 