apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "plausible.fullname" . }}
  labels:
    {{- include "plausible.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "plausible.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "plausible.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              /entrypoint.sh db createdb && \
              /entrypoint.sh db migrate && \
              /entrypoint.sh run
          ports:
            - name: http
              containerPort: 8000
          resources:
            {{- toYaml .Values.resources.plausible | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "plausible.fullname" . }}-config
          env:
            - name: DATABASE_URL
              value: postgres://{{ .Values.postgresql.user }}:$(POSTGRES_PASSWORD)@{{ .Values.postgresql.host }}:{{ .Values.postgresql.port }}/{{ .Values.postgresql.database }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: plausible-secrets
                  key: postgres-password
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: plausible-secrets
                  key: secret-key-base 