apiVersion: v1
kind: Service
metadata:
  name: {{ include "plausible.fullname" . }}
  labels:
    {{- include "plausible.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8000
      name: http
  selector:
    {{- include "plausible.selectorLabels" . | nindent 4 }} 