apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "plausible.fullname" . }}-config
  labels:
    {{- include "plausible.labels" . | nindent 4 }}
data:
  BASE_URL: {{ .Values.config.baseUrl }}
  CLICKHOUSE_DATABASE_URL: http://{{ include "plausible.fullname" . }}-clickhouse:{{ .Values.clickhouse.service.port }}/plausible
  DISABLE_REGISTRATION: {{ .Values.config.disableRegistration | quote }}
  MAILER_EMAIL: {{ .Values.config.smtp.fromEmail }}
  SMTP_HOST_ADDR: {{ .Values.config.smtp.host }}
  SMTP_HOST_PORT: {{ .Values.config.smtp.port | quote }}
  SMTP_HOST_SSL_ENABLED: {{ .Values.config.smtp.sslEnabled | quote }}
  SMTP_USER_NAME: {{ .Values.config.smtp.user }}
  SMTP_USER_PWD: {{ .Values.config.smtp.password }} 